description: MCP23017 GPIO controller

compatible: "microchip,mcp23017"

include: [gpio-controller.yaml, i2c-device.yaml]

properties:
  "#gpio-cells":
    const: 2

  ngpios:
    type: int
    required: true
    description: Number of GPIOs available

gpio-cells:
  - pin
  - flags
