on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Cache clear comment - 20240615
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      shield: 'chocolatebox'